### ISSUE TITLE
Spring / Rules contexts

### ISSUE THREAD

**Issue by rodriguezc** [EasyRules/easyrules#23] opened 2015-11-04 13:05 UTC
Thank you for this promising project.

The interest of Spring is very limited with the actual implementation.

Perhaps it could be interesting to set a context to a RulesEngine like this:
rulesEngine.addContext("age", 18);
or
rulesEngine.fireRules("age", 18, "gender", "Male");

And to set dynamically the context to the rule during the execution:
In the pojo:
@Rule(...)
public class AgeRule {
  @Context("age") //injected by the ruleEngine
  private Long age;
}

**Comment by benas** [comment] 2015-11-04 19:02
Hi, thank you!

> The interest of Spring is very limited with the actual implementation.

The main advantage of using Easy Rules with Spring is the ability to configure the engine and register/unregister rules through the Xml configuration without recompiling the application.

> it could be interesting to set a context to a RulesEngine

This is a good idea indeed. There is an interesting [fork](https://github.com/augusto/MintRules) of Easy Rules that introduces the concept of session which is a context object like you suggest. [Here is an example](https://github.com/augusto/MintRules/blob/master/mintrules-samples/src/main/java/org/mintrules/samples/decision/DecisionExample.java#L26). What are your thoughts on this idea?

**Comment by rodriguezc** [comment] 2015-11-05 07:15
I like it. I think the same: 

"The rules in EasyRules are usually stateful which leads to having to create a new rules engine per thread, this is the price to pay for the beauty and simplicity of EasyRules."

The concept of Spring batch can be compared to easy-rules.
-A job can be compared to an engine
-A step can be compared to a rule
-Listeners can be executed before and after job or step execution

A spring job can be fully defined with annotations.
A step can easily use services and sessions data:
Spring batch has custom scopes for injecting the session during the execution
@StepScope, @JobScope

I think that it could be possible to do a similar implementation.

**Comment by benas** [comment] 2015-11-11 23:43
First, let me add @augusto (the author of MintRules) to this thread because I think this discussion will be very interesting in terms of API design.

Second, I do apologize for the long comment, I couldn't do shorter..

@augusto I cited MintRules in my last comment because I like the idea of the session object you introduced.

----

> The rules in EasyRules are usually stateful which leads to having to create a new rules engine per thread, this is the price to pay for the beauty and simplicity of EasyRules.

* Rules in Easy Rules are designed to be stateful (and this **could be** a design issue, but I'm not sure, I'll explain why). A rule is designed to encapsulate the Business Object Model, conditions and actions all together. This is all we need to define a business rule that follows the BDD pattern Given/When/Then which makes it easy to understand, implement and unit test in isolation (from the rules engine). Here is an example of rule in a web app (that I gave in issue #16):

```java
@Rule (name = "IpFilteringRule", description="Filter users with suspicious IPs" )
public class IpFilteringRule {

    private HttpServletRequest request; // the BOM // Given

    public IpFilteringRule(HttpServletRequest request) {
        this.request = request;
    }

    @Condition // test against the BOM, // When
    public boolean whenRequestIsSuspicious() {
        return request.getRemoteAddr().contains("10.26.65.98"); // change this to a configurable range of IPs
    }

    @Action // act upon the BOM // Then
    public void thenFilterRequest() {
        request.addAttribute("suspicious", true); 
    }

}
```

Since a rule is usually stateful, it is not thread-safe (except if we synchronize it's state, but this is not what we want for performance reason). Now, rules are *not* thread-safe, what's wrong with that? I would like each thread to operate on his own instance, this is more secure and easier than making all rules and the rules engine thread safe and try to share the same instance across all threads. 

* In regards to "which leads to having to create a new rules engine per thread", a `RulesEngine` object is very lightweight! It is just a `Set<Rules>`. If you got a `Set<Object>` in your application, would you create a `Set<Object>` per thread or try to encapsulate it in a thread-safe class that you would share across all threads? To my opinion, I would create a `Set<Object>` per thread which is finally the safest solution.
This is the same for `RulesEngine`. And by the way, the `RulesFactoryBean` has been designed to create protoyped scoped `RulesEngine` for [this reason](https://gitter.im/benas/easy-rules?at=5595b525fcbe8872682ec77e). I strongly believe in "Premature optimization is the root of all evil" by Donald Knuth, when we say "have to create a new rules engine per thread" we are may be bothering about performance prematurely and it happens that it could work efficiently without any problem.

Anyway, this design **could be wrong!** and is subject to discussion.

A quick note about Mint Rules examples:

* The session object is [not thread safe](https://github.com/augusto/MintRules/blob/master/mintrules-core/src/main/java/org/mintrules/api/Session.java#L9). This is a good point :+1: Each thread should create his own session object
* [Example 1](https://github.com/augusto/MintRules/tree/master/mintrules-samples/src/main/java/org/mintrules/samples/decision) : The rule `ChargeRule` is not thread safe (it has a unsynchronized state) and the engine is not usable as is in a multi-threaded environment even with a session object
* [Example 2](https://github.com/augusto/MintRules/tree/master/mintrules-samples/src/main/java/org/mintrules/samples/validation): This is a very good sample! Rules are thread safe and take the BOM reference as parameter in both condition and action (no state => thread safe). But the engine is not thread safe! What if two threads fire rules with different sessions, the single engine instance would iterate through the set of rules (which is unsychronized) and may lead to thread safety issues. Do you agree? If yes, than even with MintRules we need to create a rules engine per thread.

Let's turn the previous `IpFilteringRule` into a thread-safe version by eliminating the state and passing the BOM as parameter (inspired by example 2 of MintRules):

```java
@Rule (name = "IpFilteringRule", description="Filter users with suspicious IPs" )
public class IpFilteringRule {

    @Condition // test against the BOM, // When
    public boolean whenRequestIsSuspicious(final HttpServletRequest request) {
        return request.getRemoteAddr().contains("10.26.65.98"); // change this to a configurable range of IPs
    }

    @Action // act upon the BOM // Then
    public void thenFilterRequest(final HttpServletRequest request) {
        request.addAttribute("suspicious", true); 
    }

}
```

Now, the question is : If we register multiple thread-safe rules in the same rules engine, does the rules engine still thread safe?

If yes, than Easy Rules has a design issue that I should admit and accept to improve it!!
If not, than Easy Rules could continue as is today.

@rodriguezc I like the analogy with Spring Batch (even though I prefer [Easy Batch](https://github.com/EasyBatch/easybatch-framework) :-) )
The idea of injecting context information though annotation is very elegant and coherent with the annotation programming model of Easy Rules. Thank you for this suggestion, this should definitely be added to Easy Rules if we decide to implement context objects!

@augusto, @rodriguezc I would love to hear your thoughts about this analysis.

**Comment by rodriguezc** [comment] 2015-11-12 07:22
I have implemented a basic prototype of my idea of a rule engine:
https://github.com/rodriguezc/spring-rules
it is fully Spring dependant...
it use ThreadLocal...
it use proxies...
it is possible to design a complex rules flow (inspired by Spring batch)
(I'll be happy to have a feedback from you)

Most of projects "in the world" use Spring Framework. And Spring is based on Proxies and ThreadLocal.

Your solution is statefull but... you also use proxies and proxies are a performance issue... I know it is possible to inject a bean that implements the Rule interface but we like annotations...

In my experience, performances issues are in general in persistence layer: wrong usage of JPA, transactions, SQL optimisations etc. And resolving them is enough.

The beauty of the code causes performances issues.
What is the limit? It is not possible to answer easily because every projects has its own requirements. I think that in most of projects this will not be a problem. 
Voilà :)

**Comment by benas** [comment] 2015-11-12 10:08
> Spring is based on Proxies
> proxies are a performance issue
Should I conclude that "Spring is a performance issue" ? :-)

Using a Proxy to transform a plain object annotated with a couple of annotations into a Rule is the most elegant way that I could come up with to fix the ugly version 1.x of Easy Rules (issue #12).

> The beauty of the code causes performances issues.

That confirms what @augusto said about Easy Rules:

> This is the price to pay for the beauty and simplicity of EasyRules.

There is not a silver bullet solution. We can't have the cake and eat it too.

But I agree with you, every projects has its own requirements, and we should be pragmatic!

I'll take a look at your implementation, looks promising. You project name is great! You should consider implement the JSR 94 with Spring  and propose "Spring Rules" to pivotal. It may be incubated and why not become one project in their portfolio. Wish you all the best if you invest time on this!

On my side, even I'm a big fan of Spring, I didn't want to make Easy Rules Spring dependent :-) Just so my Guice friends are not angry :-)

**Comment by augusto** [comment] 2015-11-12 17:46
Hi @benas and @rodriguezc!

Sorry for the late reply, I've been away for a few days :). I don't think I have much to say as it looks like the conversation reached a plateau, but I just wanted to mention one thing.

Over time, I like more and more the idea of the stateful rules. I think this removes a lot of the magic and becomes really easy to reason, so easy, that understanding how EasyRules works takes less less than 5 minutes. The only 'performance' impact is the (re)allocation of the rules object, which is not that bad.

About the thread-safety issues, you're right that the engine is not thread-safe and I should fix that. In the context I've been using MintRules (with Spring and having 'singleton' Engines) the thread-safety was enforced with *happens-before* operations outside the rules engine (spring guarantees this). The other reason is that rules were mostly immutable (final fields) and the fields that weren't immutable, were volatile... (I have the feeling I navigated through a minefield without triggering any explosions).

**Comment by benas** [comment] 2015-11-17 11:07
Hi @augusto,

Thank you for your reply

> I like more and more the idea of the stateful rules. I think this removes a lot of the magic and becomes really easy to reason

I do agree!

> The only 'performance' impact is the (re)allocation of the rules object, which is not that bad

Same here, I used to learn to deal with performance problems when they occur, not before..

I see your use case with Spring, you should may be take a look at spring-rules by @rodriguezc

BTW, @rodriguezc, I've got some time to take a look at spring-rules, here is my feedback, as promised:

* I like the idea of flow/transition, this in fact makes it possible to create complex rules flows :+1: 
* Kudos for the custom "rule" scope! But since you have spring in your toolbox, you should not do context injection [by hands](https://github.com/rodriguezc/spring-rules/blob/master/src/main/java/org/iperlon/rules/core/scope/RuleScopeImpl.java#L31), try to find a way to make Spring does it for you
* Not sure I understand the `RulesGame` abstraction
* Rules are still stateful (the state is annotated with `@Context`), but you had to introduce a `RulesGameSynchronizationManager` with ThreadLocals, [setting](https://github.com/rodriguezc/spring-rules/blob/master/src/main/java/org/iperlon/rules/core/engine/SimpleRulesGame.java#L38) and [removing](https://github.com/rodriguezc/spring-rules/blob/master/src/main/java/org/iperlon/rules/core/engine/SimpleRulesGame.java#L51) the context for each rule, etc.. I think (but I'm not sure :smile:) this is the magic @augusto is talking about and that I decided to avoid by design in Easy Rules. But it is fine in your context. I think the most efficient way is to make rules stateless and pass the context as parameter in when/then method (like in MintRules)

Let's return to the context of the feature request you created, I've implemented context injection (in a local branch) in Easy Rules and here is an example:

```java
@Rule
class MyRule {
    @Context (key = "foo")
    private int value;
    // setter for value, condition and action methods
}

RulesEngine engine = ..
MyRule rule = new MyRule();
engine.registerRule(rule);
engine.setContext("foo", 10);
engine.fireRules();
```

But, from the user's point of view, what is the added value of:

* adding the `@Context` annotation on the field
* setting the context object in the engine and let the engine inject it

compared to setting directly the value on the rule itself?

```java
RulesEngine engine = ..
MyRule rule = new MyRule();
rule.setValue(10);
engine.registerRule(rule);
engine.fireRules();
```

Do you see the point? IMO, The second approach is more straightforward and requires less code for the client and Easy Rules (I found my self creating a mini-Spring to implement injection..)

I understand now more your statement:

> The interest of Spring is very limited with the actual implementation.

I think context injection is more valuable in a Spring managed environment (spring-rules for instance) than Easy Rules. Do you agree?

**Comment by rodriguezc** [comment] 2015-11-23 12:38
Thank you for you feedback!
IOC permits to add extra features.
But I agree with you. And the main goal of Easy rules is to have a simple / easy to understand rule engine.
See you!

**Comment by benas** [comment] 2016-05-04 06:21
Hi @rodriguezc 

I was thinking to add support for evaluating rules using an Expression Language (#36).
The `EvaluationContext` of SpEL is a good place to put context objects against which rules can be evaluated.

A quick draft example:

```java
Context context = new Context();
context.add(new Person("tom", 20)); // name, age

RulesEngine engine = ..
engine.registerRule("age > 18", "this.action"); // need to find a way define action on the current context object

engine.fireRule(context); // fire rules against a context
```

I would love to hear your thoughts!
Kind regards
Mahmoud

**Comment by rodriguezc** [comment] 2016-06-27 11:54
Hi @benas 
Sorry for the delay. 
At the beginning I was searching for a rule engine but I have finally decided to integrate the Groovy scripts engine in my Spring / JAVA project. The scripts are stored in the file system and I can reload them at runtime. I call these scripts from java classes. Intellij has a very good integration with .groovy files. EL is a good choice. Spring Websocket uses it for expressions on topic subscriptions.
DSL would be nice too ;)
You just need to create a maven archetype that generates java code in order to use the variables ;)
engine.registerRule(age.gt(18), ...)

See you
Chris

**Comment by benas** [comment] 2017-05-13 21:42
Hi @rodriguezc 

I've been working on "Context injection" for v3. The context is a set of facts against which rules can be evaluated. Easy Rules will inject facts in condition and action methods of rules ( see #37 ).

This new design should address thread safety issues of v2. The rules and the engine are both stateless now.

> The interest of Spring is very limited with the actual implementation.

BTW, Spring support will be discontinued starting from v3 ( see #74 )

I'm closing this issue for now, context injection can be discussed in #37 

Kr
Mahmoud

**Closed by benas** 2017-05-13 21:42 UTC
Labels: enhancement, Feature, Major API change

**Comment by zhhaojie** [comment] 2019-05-06 10:11
wow. that's a very very long story about easy-rules.
my company planing to open source a project on `easy-rules` .
i hope it would not take too long .
